name: weather
description: A new Flutter project.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: any
  flutter_svg: any
  http: any
  intl: any
  animated_splash_screen: any
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/aqi/
    - assets/icon/
    - assets/search/
    - assets/weather/